version: '3.3'
services:
  web:
    image: ptisserand/stock-sync-to-drive:latest
    volumes:
      - ./config:/config
      - ./db:/db
    environment:
      - CONFIG_DIR=/config
      - DB_DIR=/db
      - FLASK_APP=web
